{% set name = "neworder" %}
{% set version = "0.1.2" %}
{% set sha256 = "9ecf71672bf2d9441f0417b5bdf27628cc4850591e1f0fe3e3e80134a7baf6ad" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/neworder-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - {{ compiler('cxx') }}
  host:
    - pip
    - pybind11 >=2.5.0
    - pytest-runner
    - python
  run:
    - numpy >=1.19.1
    - pandas >=1.0.5
    - python

test:
  imports:
    - neworder
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://neworder.readthedocs.io
  summary: A dynamic microsimulation framework
  license: MIT
  license_file: LICENCE

extra:
  recipe-maintainers:
    - virgesmith
