{% set name = "neworder" %}
{% set version = "0.3.0" %}
{% set sha256 = "26887ae7cc767ffa367b3c4aa0c91a7339c1fb0b1994db0101799589f2ae0fd3" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/neworder-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - {{ compiler('cxx') }}
  host:
    - pip
    - pybind11 >=2.5.0
    - pytest-runner
    - python
  run:
    - numpy >=1.19.1
    - pandas >=1.0.5
    - python

test:
  imports:
    - neworder
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://neworder.readthedocs.io
  summary: A dynamic microsimulation framework
  license: MIT
  license_file: LICENCE.md

extra:
  recipe-maintainers:
    - virgesmith
